### ISSUE TITLE
My fps is very low.

### ISSUE THREAD

**Issue by qqdasb** [MastaG/mesa-turnip-ppa#3]
My GPU is Adreno 615
glmark2 has a maximum of 30fps.vkmark's is only about 70fps.
Adreno 619's glmark2 fps is about 200fps,when dri3 is turned on, the fps can be doubled.
I don't know why the fps of Adreno 615 is so low.
There is my envionment variables:
```bash
TU_DEBUG=noconform
MESA_VK_PRESENT_MODE=mailbox
vblank_mode=0
```
I'm using Ubuntu 24.10 from proot-distro.

**Comment by MastaG** [comment]
The builds are currently failing for 24.10.
So you're getting a very outdated build from the repository.
I'll have to report this to the mesa issue tracker.
I'll do this after my vacation.
Currently only 24.04 has nightly packages built correctly.

Also keep in mind that asside from 24.10 not building since a few weeks.
I'm not applying any open/wip merge requests or other unofficial patches.

I only apply the dri3 patch and the build flag for enabling kgsl support, nothing else.
That's why people see better performance when using other popular turnip builds such as the one from airidosas252 
https://t.me/airidosas252builds

Also another thing to keep in mind, that if you're main goal is playing games.
You might want to skip on proot and use termux glibc native or chroot.
